apiVersion: apps/v1
kind: Deployment
metadata:
  name: edge-service
  labels:
    app: edge-service
    version: edge-service
    service: edge-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: edge-service
      version: edge-service
      service: edge-service
  template:
    metadata:
      labels:
        app: edge-service
        version: edge-service
        service: edge-service
    spec:
      containers:
        - name: edge-service
          image: ghcr.io/gmdcjdakdcjd/edge-service:latest
          imagePullPolicy: IfNotPresent
          lifecycle:
            preStop:
              exec:
                command: ["sh", "-c", "sleep 5"]
          ports:
            - containerPort: 9000
          env:
            - name: CATALOG_SERVICE_URL
              value: http://catalog-service
            - name: ORDER_SERVICE_URL
              value: http://order-service
            - name: SPA_URL
              value: http://polar-ui
            - name: SPRING_CLOUD_CONFIG_URI
              value: http://config-service
            - name: SPRING_REDIS_HOST
              value: polar-redis
            - name: SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_ISSUER_URI
              value: http://ab1499ce512714319a3df12ec8b08c1c-941973363.ap-northeast-2.elb.amazonaws.com/realms/PolarBookshop

            # - name: SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_ISSUER_URI
            #   value: http://polar-keycloak/realms/PolarBookshop
